name: CI

on:

  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://huggingface.co/spaces/Mishaco777/demo2
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
          My_Token: ${{ secrets.GITHUB_TOKEN}}
        run: git push --force https://huggingface.co/spaces/Mishaco777/demo2 main
          
